apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "100"
        - name: TZ
          value: Australia/Melbourne
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: sabnzbd-data
          mountPath: /config
        - name: nfs-media
          mountPath: /downloads
          subPath: downloads/usenet
      volumes:
      - name: sabnzbd-data
        persistentVolumeClaim:
          claimName: sabnzbd-data-pvc
      - name: nfs-media
        persistentVolumeClaim:
          claimName: media-server-nfs-pvc
