apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: n8n
  releaseName: n8n
  namespace: automation
  version: 1.0.6
  repo: oci://8gears.container-registry.com/library
