apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize

helmCharts:
- name: traefik
  releaseName: traefik
  namespace: networking
  version: 34.3.0
  repo: https://traefik.github.io/charts
