apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "100"
        - name: TZ
          value: Australia/Melbourne
        ports:
        - name: http
          containerPort: 7878
          protocol: TCP
        volumeMounts:
        - name: radarr-data
          mountPath: /config
        - name: nfs-media
          mountPath: /media
      volumes:
      - name: radarr-data
        persistentVolumeClaim:
          claimName: radarr-data-pvc
      - name: nfs-media
        persistentVolumeClaim:
          claimName: media-server-nfs-pvc
