apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize

helmCharts:
- name: longhorn
  releaseName: longhorn
  namespace: longhorn
  version: 1.7.2
  repo: https://charts.longhorn.io
  valuesInline:
    ingress:
      ## Set to true to enable ingress record generation
      enabled: true
      host: longhorn.home

      defaultSettings:
        backupTarget: "nfs://192.168.20.21:/mnt/user/longhorn-backup"
    persistence:
      defaultClassReplicaCount: 1
