longhorn:
  ingress:
    ## Set to true to enable ingress record generation
    enabled: true
    host: longhorn.home

    defaultSettings:
      defaultClassReplicaCount: 1 # Set this to 1 for single-node cluster
