longhorn:
  ingress:
    ## Set to true to enable ingress record generation
    enabled: true
    host: longhorn.home

    defaultSettings:
      backupTarget: "nfs://192.168.20.21:/mnt/user/longhorn-backup"
  persistence:
    defaultClassReplicaCount: 1
