apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize

helmCharts:
- name: argo-cd
  releaseName: argocd
  namespace: argocd
  version: 7.8.2
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
