apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../../charts
helmCharts:
- name: argo-cd
  releaseName: argocd
  namespace: argocd
  version: 7.8.27
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
