apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: op-secret-store
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect:8080
      vaults:
        homelab: 1  # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepass-homelab-connect-token
            key: token
