apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize

helmCharts:
- name: metallb
  releaseName: metallb
  namespace: networking
  version: 0.14.9
  repo: https://metallb.github.io/metallb

resources:
  - ./resources/ip-address-pool.yaml
  - ./resources/l2-advertisement.yaml
