apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize
resources:
  - ./resources/deployment.yaml
  - ./resources/mc-br-svc.yaml
  - ./resources/pvc.yaml
