apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize

helmCharts:
- name: ingress-nginx
  releaseName: external-dns
  namespace: networking
  version: 4.10.1
  repo: https://kubernetes.github.io/ingress-nginx
  valuesInline:
    controller:
      ingressClassResource:
        name: nginx-internal
        enabled: true
        default: true
        controllerValue: "k8s.io/ingress-nginx"
        parameters: {}
