apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize

helmCharts:
- name: pihole
  releaseName: pihole
  namespace: networking
  version: 2.27.0
  repo: https://mojo2600.github.io/pihole-kubernetes/
  valuesFile: values.yaml
