apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize

helmCharts:
- name: external-secrets
  releaseName: external-secrets
  namespace: security
  version: 0.12.1
  repo: https://charts.external-secrets.io
