apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-nfs-pv
spec:
  capacity:
    storage: 24Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/user/media
    server: 192.168.20.21
