apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-server-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
  storageClassName: "" # Prevent Longhorn from overtaking
