apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: crossplane
  releaseName: crossplane
  namespace: cloud
  version: 2.0.0-rc.0.281.ga8fefac61
  repo: https://charts.crossplane.io/stable
  valuesFile: values.yaml
