apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: crossplane
  releaseName: crossplane
  namespace: cloud
  version: 1.2.0
  repo: https://charts.crossplane.io/stable
  valuesFile: values.yaml
