apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize

helmCharts:
- name: kube-prometheus-stack
  releaseName: kube-prometheus-stack
  namespace: monitoring
  version: 70.7.0
  repo: https://prometheus-community.github.io/helm-charts
  includeCRDs: true

patches:
  - target:
      kind: CustomResourceDefinition
    path: patches/crd.yaml
