apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  namespace: security
  version: 1.17.1
  repo: https://charts.jetstack.io
  valuesInline:
    global:
      leaderElection:
        namespace: security
    installCRDs: true
