apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: plex-media-server
  releaseName: plex-media-server
  namespace: media-server
  version: 0.8.0
  repo: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
  valuesFile: values.yaml
