plex-media-server:
  # -- The docker image information for the pms application
  image:
    registry: lscr.io
    repository: linuxserver/plex

  ingress:
    enabled: true
    url: "plex.home"

  pms:
    # -- The volume size to provision for the PMS database
    configStorage: 50Gi

    # -- Name of an existing `PersistentVolumeClaim` for the PMS database
    # NOTE: When set, 'configStorage' and 'storageClassName' are ignored.
    configExistingClaim: "plex-data-pvc"

    # Enabling this will add nvidia.com/gpu: 1 to limits, and will set
    # environment for the nvidia operator
    gpu:
      nvidia:
        enabled: false

    resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  service:
    type: NodePort
    port: 32400
    nodePort: 32400
    externalTrafficPolicy: Local


  extraEnv:
    HOSTNAME: "Skhtor"
    TZ: "Australia/Melbourne"
    PLEX_UID: "1000"
    PLEX_GID: "100"

  # -- Optionally specify additional volume mounts for the PMS and init containers.
  extraVolumeMounts: []
  # extraVolumeMounts:
  #   - name: dev-dri
  #     mountPath: /dev/dri

  # -- Optionally specify additional volumes for the pod.
  extraVolumes: []
  # extraVolumes:
  #   - name: dev-dri
  #     hostPath:
  #       path: /dev/dri
  #       type: Directory
