apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-time-slicing
data:
  time-slicing: |-
    version: v1
    sharing:
      timeSlicing:
        resources:
          - name: nvidia.com/gpu
            replicas: 10
