apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize
resources:
  - ./resources/ip-address-pool.yaml
  - ./resources/l2-advertisement.yaml
