apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize

helmCharts:
- name: metrics-server
  releaseName: metrics-server
  namespace: kube-system
  version: 3.12.2
  repo: https://kubernetes-sigs.github.io/metrics-server/
