apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
      - name: nzbget
        image: lscr.io/linuxserver/nzbget
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "100"
        - name: TZ
          value: Australia/Melbourne
        ports:
        - name: http
          containerPort: 6789
          protocol: TCP
        volumeMounts:
        - name: nzbget-data
          mountPath: /config
        - name: nfs-media
          mountPath: /downloads
          subPath: downloads/usenet
      volumes:
      - name: nzbget-data
        persistentVolumeClaim:
          claimName: nzbget-data-pvc
      - name: nfs-media
        persistentVolumeClaim:
          claimName: media-server-nfs-pvc
