apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize
resources:
  - ./resources/deployment.yaml
  - ./resources/ingress.yaml
  - ./resources/pvc.yaml
  - ./resources/service.yaml
