apiVersion: v1
kind: Service
metadata:
  name: pufferpanel-svc
  namespace: networking
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.20.250
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app: pihole
    release: pihole
  type: LoadBalancer


apiVersion: v1
kind: Service
metadata:
  name: pufferpanel-web
  namespace: gaming
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: pufferpanel
  type: ClusterIP
