apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: lscr.io/linuxserver/plex
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,video,utility"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "100"
        - name: VERSION
          value: "docker"
        - name: TZ
          value: Australia/Melbourne
        ports:
        - name: http
          containerPort: 32400
          protocol: TCP
        volumeMounts:
        - name: plex-data
          mountPath: /config
        - name: nfs-media
          mountPath: /live
          subPath: live
        resources:
          requests:
            cpu: 2   # Reserves 0.5 vCPU for Plex
            memory: "4Gi" # Ensures Plex always has at least 2GB RAM
      volumes:
      - name: plex-data
        persistentVolumeClaim:
          claimName: plex-data-pvc
      - name: nfs-media
        persistentVolumeClaim:
          claimName: media-server-nfs-pvc
