apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media-server
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: plex
  type: ClusterIP
