gotify:
  server:
    timezone: Australia/Melbourne
  ingress:
    enabled: true
    hosts:
      - host: gotify.home
        paths:
          - path: /
            pathType: ImplementationSpecific
  persistence:
    enabled: true
    size: 10Gi
