apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize

helmCharts:
- name: connect
  releaseName: 1password-connect
  namespace: security
  version: 1.17.0
  repo: https://1password.github.io/connect-helm-charts
  valuesInline:
    operator:
      token:
        key: onepass-homelab-connect-token
