apiVersion: v1
kind: Service
metadata:
  name: minecraft-br-udp
  namespace: gaming
spec:
  ports:
    - name: udp
      port: 19132
      protocol: UDP
      targetPort: udp
  selector:
    app: minecraft-br
  type: ClusterIP
