apiVersion: v1
kind: Service
metadata:
  name: minecraft-br-udp
  namespace: gaming
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.20.193
  ports:
    - name: udp
      port: 19132
      protocol: UDP
      targetPort: udp
  selector:
    app: minecraft-br
  type: LoadBalancer
